// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	restaurant "github.com/programming-kubernetes/pizza-apiserver/pkg/apis/restaurant"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Pizza)(nil), (*restaurant.Pizza)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Pizza_To_restaurant_Pizza(a.(*Pizza), b.(*restaurant.Pizza), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.Pizza)(nil), (*Pizza)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_Pizza_To_v1beta1_Pizza(a.(*restaurant.Pizza), b.(*Pizza), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PizzaList)(nil), (*restaurant.PizzaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PizzaList_To_restaurant_PizzaList(a.(*PizzaList), b.(*restaurant.PizzaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.PizzaList)(nil), (*PizzaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_PizzaList_To_v1beta1_PizzaList(a.(*restaurant.PizzaList), b.(*PizzaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PizzaSpec)(nil), (*restaurant.PizzaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec(a.(*PizzaSpec), b.(*restaurant.PizzaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.PizzaSpec)(nil), (*PizzaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec(a.(*restaurant.PizzaSpec), b.(*PizzaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PizzaStatus)(nil), (*restaurant.PizzaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus(a.(*PizzaStatus), b.(*restaurant.PizzaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.PizzaStatus)(nil), (*PizzaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus(a.(*restaurant.PizzaStatus), b.(*PizzaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PizzaTopping)(nil), (*restaurant.PizzaTopping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PizzaTopping_To_restaurant_PizzaTopping(a.(*PizzaTopping), b.(*restaurant.PizzaTopping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*restaurant.PizzaTopping)(nil), (*PizzaTopping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_restaurant_PizzaTopping_To_v1beta1_PizzaTopping(a.(*restaurant.PizzaTopping), b.(*PizzaTopping), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_Pizza_To_restaurant_Pizza(in *Pizza, out *restaurant.Pizza, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Pizza_To_restaurant_Pizza is an autogenerated conversion function.
func Convert_v1beta1_Pizza_To_restaurant_Pizza(in *Pizza, out *restaurant.Pizza, s conversion.Scope) error {
	return autoConvert_v1beta1_Pizza_To_restaurant_Pizza(in, out, s)
}

func autoConvert_restaurant_Pizza_To_v1beta1_Pizza(in *restaurant.Pizza, out *Pizza, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_restaurant_Pizza_To_v1beta1_Pizza is an autogenerated conversion function.
func Convert_restaurant_Pizza_To_v1beta1_Pizza(in *restaurant.Pizza, out *Pizza, s conversion.Scope) error {
	return autoConvert_restaurant_Pizza_To_v1beta1_Pizza(in, out, s)
}

func autoConvert_v1beta1_PizzaList_To_restaurant_PizzaList(in *PizzaList, out *restaurant.PizzaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]restaurant.Pizza)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_PizzaList_To_restaurant_PizzaList is an autogenerated conversion function.
func Convert_v1beta1_PizzaList_To_restaurant_PizzaList(in *PizzaList, out *restaurant.PizzaList, s conversion.Scope) error {
	return autoConvert_v1beta1_PizzaList_To_restaurant_PizzaList(in, out, s)
}

func autoConvert_restaurant_PizzaList_To_v1beta1_PizzaList(in *restaurant.PizzaList, out *PizzaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Pizza)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_restaurant_PizzaList_To_v1beta1_PizzaList is an autogenerated conversion function.
func Convert_restaurant_PizzaList_To_v1beta1_PizzaList(in *restaurant.PizzaList, out *PizzaList, s conversion.Scope) error {
	return autoConvert_restaurant_PizzaList_To_v1beta1_PizzaList(in, out, s)
}

func autoConvert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec(in *PizzaSpec, out *restaurant.PizzaSpec, s conversion.Scope) error {
	out.Toppings = *(*[]restaurant.PizzaTopping)(unsafe.Pointer(&in.Toppings))
	return nil
}

// Convert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec is an autogenerated conversion function.
func Convert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec(in *PizzaSpec, out *restaurant.PizzaSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PizzaSpec_To_restaurant_PizzaSpec(in, out, s)
}

func autoConvert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec(in *restaurant.PizzaSpec, out *PizzaSpec, s conversion.Scope) error {
	out.Toppings = *(*[]PizzaTopping)(unsafe.Pointer(&in.Toppings))
	return nil
}

// Convert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec is an autogenerated conversion function.
func Convert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec(in *restaurant.PizzaSpec, out *PizzaSpec, s conversion.Scope) error {
	return autoConvert_restaurant_PizzaSpec_To_v1beta1_PizzaSpec(in, out, s)
}

func autoConvert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus(in *PizzaStatus, out *restaurant.PizzaStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus is an autogenerated conversion function.
func Convert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus(in *PizzaStatus, out *restaurant.PizzaStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_PizzaStatus_To_restaurant_PizzaStatus(in, out, s)
}

func autoConvert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus(in *restaurant.PizzaStatus, out *PizzaStatus, s conversion.Scope) error {
	out.Cost = in.Cost
	return nil
}

// Convert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus is an autogenerated conversion function.
func Convert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus(in *restaurant.PizzaStatus, out *PizzaStatus, s conversion.Scope) error {
	return autoConvert_restaurant_PizzaStatus_To_v1beta1_PizzaStatus(in, out, s)
}

func autoConvert_v1beta1_PizzaTopping_To_restaurant_PizzaTopping(in *PizzaTopping, out *restaurant.PizzaTopping, s conversion.Scope) error {
	out.Name = in.Name
	out.Quantity = in.Quantity
	return nil
}

// Convert_v1beta1_PizzaTopping_To_restaurant_PizzaTopping is an autogenerated conversion function.
func Convert_v1beta1_PizzaTopping_To_restaurant_PizzaTopping(in *PizzaTopping, out *restaurant.PizzaTopping, s conversion.Scope) error {
	return autoConvert_v1beta1_PizzaTopping_To_restaurant_PizzaTopping(in, out, s)
}

func autoConvert_restaurant_PizzaTopping_To_v1beta1_PizzaTopping(in *restaurant.PizzaTopping, out *PizzaTopping, s conversion.Scope) error {
	out.Name = in.Name
	out.Quantity = in.Quantity
	return nil
}

// Convert_restaurant_PizzaTopping_To_v1beta1_PizzaTopping is an autogenerated conversion function.
func Convert_restaurant_PizzaTopping_To_v1beta1_PizzaTopping(in *restaurant.PizzaTopping, out *PizzaTopping, s conversion.Scope) error {
	return autoConvert_restaurant_PizzaTopping_To_v1beta1_PizzaTopping(in, out, s)
}
